### ISSUE TITLE
ID collisions for embedded schemas

### ISSUE THREAD

**Issue by Rio517** [tfwright/live_admin#40]
**Describe the bug**
It seems that embedded schemas that call LiveAdmin.Components.Container.Form.ArrayInput creates ID collisions.  I tried 0.8.0 and current main.

Relevant Resource schema 
``` 
schema "profiles" do
    embeds_many(:skills, Skill, on_replace: :delete)
end
```

Embeded schema:
```
  embedded_schema do
    field(:eagerness, :integer)
    field(:label, :string)
    field(:seniority, :integer)
  end
```

Error message: 
```
** (RuntimeError) found duplicate ID :skills for component LiveAdmin.Components.Container.Form.ArrayInput when rendering template
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:635: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 4.3) maps.erl:411: :maps.fold_1/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:628: Phoenix.LiveView.Diff.render_pending_components/6
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:833: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:469: Phoenix.LiveView.Channel.mount_handle_params_result/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:1041: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {Phoenix.Channel, %{"params" => %{"_csrf_token" => "GAsPMxpgZxoTPQoafxBnFGMBAhczVBE9YZZVkMWuFK977iJn0tAzKyxo", "_mounts" => 0}, "session" => "SFMyNTY.g2gDaAJhBXQAAAAIZAACaWRtAAAAFHBoeC1GMnFtUHVQMXlNWV9DZ1FHZAAMbGl2ZV9zZXNzaW9uaAJkAApsaXZlX2FkbWlubggAeca6BkCdahdkAApwYXJlbnRfcGlkZAADbmlsZAAIcm9vdF9waWRkAANuaWxkAAlyb290X3ZpZXdkACVFbGl4aXIuTGl2ZUFkbWluLkNvbXBvbmVudHMuQ29udGFpbmVyZAAGcm91dGVyZAAZRWxpeGlyLlBldGFsUHJvV2ViLlJvdXRlcmQAB3Nlc3Npb250AAAAA20AAAAJcmVzb3VyY2VzbAAAAARkABpFbGl4aXIuUGV0YWxQcm8uVXNlcnMuVXNlcmQAGEVsaXhpci5QZXRhbFByby5Kb2JzLkpvYmgCZAAgRWxpeGlyLlBldGFsUHJvLlByb2ZpbGVzLlByb2ZpbGVsAAAAA2gCZAANaGlkZGVuX2ZpZWxkc2wAAAADZAAHaGlzdG9yeWQACml0ZXJhdGlvbnNkAAh2ZXJzaW9uc2poAmQAEGltbXV0YWJsZV9maWVsZHNsAAAABGQACnVwZGF0ZWRfYXRkAAtpbnNlcnRlZF9hdGQAC2Rpc3BsYXlfcmVmZAAEdXVpZGpoAmQACmxhYmVsX3dpdGhkAAtkaXNwbGF5X3JlZmpoAmQAIkVsaXhpci5QZXRhbFByby5Qcm9zcGVjdHMuUHJvc3BlY3RsAAAAA2gCZAANaGlkZGVuX2ZpZWxkc2wAAAABZAAHaGlzdG9yeWpoAmQAEGltbXV0YWJsZV9maWVsZHNsAAAABGQACnVwZGF0ZWRfYXRkAAtpbnNlcnRlZF9hdGQAC2Rpc3BsYXlfcmVmZAAEdXVpZGpoAmQACmxhYmVsX3dpdGhkAAtkaXNwbGF5X3JlZmpqbQAAAApzZXNzaW9uX2lkbQAAACRlMjZjYzU1OS1jYTYyLTQwMWQtYTQ2Yi0xNDYxNmY3NDg2NjRtAAAABXRpdGxlbQAAAAlMaXZlQWRtaW5kAAR2aWV3ZAAlRWxpeGlyLkxpdmVBZG1pbi5Db21wb25lbnRzLkNvbnRhaW5lcm4GAJYch92IAWIAAVGA.cqEG4kB-N3WCDaHpPDrWMRE2W4P-M2KuYXpVqJDozvc", "static" => "SFMyNTY.g2gDaAJhBXQAAAADZAAKYXNzaWduX25ld2pkAAVmbGFzaHQAAAAAZAACaWRtAAAAFHBoeC1GMnFtUHVQMXlNWV9DZ1FHbgYAlhyH3YgBYgABUYA.y1Mwg0fi1uBvB3mOANqEN7Ia3RtyKEo7H5OebWAe8X8", "url" => "http://local.wunderwork.io:4000/min-admin/petal_pro_prospects_prospect/edit/1"}, {#PID<0.1873.0>, #Reference<0.3783962687.1405878278.173945>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: PetalProWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: "users_sessions:etD_rWtW5t2B0rJOxzPEjxFPkDCFQl9CNomicZwPu2U=", joined: false, join_ref: "4", private: %{connect_info: %{session: %{"_csrf_token" => "AQUeq-0oUv3-Hy-zSuCmx-iR", "live_socket_id" => "users_sessions:etD_rWtW5t2B0rJOxzPEjxFPkDCFQl9CNomicZwPu2U=", "locale" => "en", "user_token" => <<122, 208, 255, 173, 107, 86, 230, 221, 129, 210, 178, 78, 199, 51, 196, 143, 17, 79, 144, 48, 133, 66, 95, 66, 54, 137, 162, 113, 156, 15, 187, ...>>}, user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"}}, pubsub_server: PetalPro.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-F2qmPuP1yMY_CgQG", transport: :websocket, transport_pid: #PID<0.1873.0>}}
State: #Reference<0.3783962687.1405878278.173948>
[error] an exception was raised:
    ** (RuntimeError) found duplicate ID :skills for component LiveAdmin.Components.Container.Form.ArrayInput when rendering template
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:635: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 4.3) maps.erl:411: :maps.fold_1/3
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:628: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:833: Phoenix.LiveView.Channel.render_diff/3
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:469: Phoenix.LiveView.Channel.mount_handle_params_result/3
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:1041: Phoenix.LiveView.Channel.verified_mount/8
        (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
        (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
        (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
        (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by tfwright** [comment]
I need a bit more information to troubleshoot this. Can you include information about specific steps to reproduce the error?

**Comment by tfwright** [comment]
I actually reproduced this while working on https://github.com/tfwright/live_admin/pull/41 and fixed it in that PR
