### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by Rio517** [tfwright/live_admin#65]
Just in case you hadn't seen it, I noticed a deprecation warning in my [newly generated app](https://github.com/Rio517/live_admin_issue), which uses a newer version of phoenix_html.

```
warning: inputs_for/3 without an anonymous function is deprecated. If you are using Phoenix.LiveView, use the new Phoenix.Component.inputs_for/1 component
  (phoenix_html 3.3.2) lib/phoenix_html/form.ex:606: Phoenix.HTML.Form.inputs_for/3
  (live_admin 0.10.1) lib/live_admin/components/resource/form/embed.ex:15: LiveAdmin.Components.Container.Form.Embed.update/2
  (phoenix_live_view 0.19.5) lib/phoenix_live_view/utils.ex:487: Phoenix.LiveView.Utils.maybe_call_update!/3
  (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:653: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
  (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (stdlib 4.3) maps.erl:411: :maps.fold_1/3
  (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:629: Phoenix.LiveView.Diff.render_pending_components/6
  (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:212: Phoenix.LiveView.Diff.write_component/4
  (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
  (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
  (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
  (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I thought I would post it for you in case you hadn't seen it.

**Comment by tfwright** [comment]
7f23434
